---
- name: Install EPEL Repo
  yum:
    name=epel-release
    state=present

- name: Install Nginx Web Server on RedHat Family
  yum:
    name=nginx
    state=latest
  when:
    ansible_os_family == "RedHat"
  notify:
    - nginx systemd

- name: Replace nginx.conf
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: "{{ root_group }}"
    mode: 0644
  notify:
    - reload nginx
