# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"

  config.vm.provider "virtualbox" do |v|
	  v.memory = 256
  end

  config.vm.define "nginx" do |machine|
    machine.vm.network "private_network", ip: "192.168.50.10", virtualbox__intnet: "dns"
    machine.vm.hostname = "nginx"
    machine.vbguest.auto_update = false
    machine.vm.network "forwarded_port", guest: 8080, host: 8080
  end

  config.vm.define "controller" do |machine|
    machine.vm.network "private_network", ip: "192.168.50.5", virtualbox__intnet: "dns"
    machine.vm.hostname = "controller"
    machine.vbguest.auto_update = false
    machine.vm.synced_folder ".vagrant", "/vagrant/.vagrant_tmp", type: "rsync"
    machine.vm.provision "shell", inline: <<-SHELL
    sed -i 's~#*ssh_args = .*~ssh_args = -o ControlMaster=auto -o ControlPersist=60s -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes~' /etc/ansible/ansible.cfg
    sed -i 's~#*host_key_checking = .*~host_key_checking = no~' /etc/ansible/ansible.cfg

    mkdir -p /vagrant/.vagrant/machines/nginx/virtualbox/
    chown -R vagrant:vagrant /vagrant/.vagrant/
    if test -f "/vagrant/.vagrant_tmp/machines/nginx/virtualbox/private_key"
    then 
      cp /vagrant/.vagrant_tmp/machines/nginx/virtualbox/private_key /vagrant/.vagrant/machines/nginx/virtualbox/private_key
      chmod 600 /vagrant/.vagrant/machines/nginx/virtualbox/private_key
      chown vagrant:vagrant /vagrant/.vagrant/machines/nginx/virtualbox/private_key
    fi
    SHELL

    machine.vm.provision :ansible_local do |ansible|
      ansible.verbose	     = "vvv"
      ansible.playbook       = "playbooks/nginx.yml"
      #ansible.verbose        = true
      ansible.install        = true
      ansible.limit          = "all"
      ansible.inventory_path = "playbooks/inventory"
    end
  end

end
